apiVersion: apps/v1
kind: Deployment
metadata:
  name:  hpa-demo
  labels:
    name:  hpa-demo
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate

  selector:
    matchLabels:
      app: hpa-demo

  template:
    metadata:
      labels:
        app:  hpa-demo

    spec:
      restartPolicy: Always

      containers:
        - name:  hpa-demo

          image:  k8s.gcr.io/hpa-example
          
          # Resource Limits
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m

          ports:
          - containerPort:  80
            name:  http